// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/upload": {
    params: {};
  };
  "/resume/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/compare": {
    params: {};
  };
  "/wipe": {
    params: {};
  };
  "/tailor": {
    params: {};
  };
  "/cover-letter": {
    params: {};
  };
  "/interview": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/upload" | "/resume/:id" | "/dashboard" | "/compare" | "/wipe" | "/tailor" | "/cover-letter" | "/interview";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/upload.tsx": {
    id: "routes/upload";
    page: "/upload";
  };
  "routes/resume.tsx": {
    id: "routes/resume";
    page: "/resume/:id";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/compare.tsx": {
    id: "routes/compare";
    page: "/compare";
  };
  "routes/wipe.tsx": {
    id: "routes/wipe";
    page: "/wipe";
  };
  "routes/tailor.tsx": {
    id: "routes/tailor";
    page: "/tailor";
  };
  "routes/cover-letter.tsx": {
    id: "routes/cover-letter";
    page: "/cover-letter";
  };
  "routes/interview.tsx": {
    id: "routes/interview";
    page: "/interview";
  };
};